@hostname = 192.168.0.13
@port = {{$dotenv FACEBOOK_WEB_CLONE_PORT}}
@url = http://{{hostname}}:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmI0M2I4Y2M5YmMyNmNkNGMwMmI0OTEiLCJpYXQiOjE3MjMwODk4MTUsImV4cCI6MTcyMzY5NDYxNX0.MJ2wmDAYrQvYihryG4ReN4rY6l-lnjd1tmLQtVd0I_o


### Auth user login (email)
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "jose@outlook.com",
  "password": "12345678"
}


### Auth user login (username)
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "jose.romero.9602",
  "password": "12345678"
}


### Auth renew user token
GET {{url}}/auth/renew
x-token: {{token}}
