@hostname = localhost
@port = {{$dotenv FACEBOOK_WEB_CLONE_PORT}}
@url = http://{{hostname}}:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmI0M2I4Y2M5YmMyNmNkNGMwMmI0OTEiLCJpYXQiOjE3MjM3NTQwNDcsImV4cCI6MTcyNDM1ODg0N30.hrtg_CgN5aZi3QBjsspdMp7wXVnompKf2ibuo-J_7Nk


### Auth user login (email)
POST {{url}}/auth/login
Content-Type: application/json

{
	"user": "aura@gmail.com",
	"password": "12345678"
}


### Auth user login (username)
POST {{url}}/auth/login
Content-Type: application/json

{
	"user": "jose.romero.9602",
	"password": "12345678"
}


### Auth renew user token
GET {{url}}/auth/renew
x-token: {{token}}
